apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ai-backend-pvc
  namespace: ai-saas

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard
