apiVersion: v1
kind: Service
metadata:
  name: ai-frontend-service
  namespace: ai-saas
spec:
  type: ClusterIP
  selector:
    app: ai-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
